### ISSUE TITLE
税込表示、税抜き表示の件

### ISSUE THREAD

**Issue by eiji0111** [webcamp-meganekko/nagano_cake_app#38]

**Comment by eiji0111** [comment]
全て共通で税込・税抜き（本体価格）を表示させた方がいいかどうか。

**Comment by Nebel-hb** [comment]
詳細画面では両方表示がいいと思いますが、
私は一覧画面ではシンプルに税込だけにしても良いかと...。
(最終的なレイアウトのイメージに合わせるのも有り)

**Comment by eiji0111** [comment]
全部統一して表示する。
