### ISSUE TITLE
レビューについて

### ISSUE THREAD

**Issue by kubotaseiko** [webcamp-meganekko/nagano_cake_app#71]
とりあえずで作ってみました。（非同期通信は未実装）
疑問点いくつかあったので教えてください！

① レビュー作成・表示画面は、以下画像の通りproductのshowで良いか
② レビュー作成者の名前不要？必要？
③ 言葉は適当に当てているので良い言葉があれば教えてください。
④ その他、あればお願いします！

![review](https://user-images.githubusercontent.com/80659433/118758734-93e2d680-b8aa-11eb-8363-f9d92c77819e.PNG)

**Comment by eiji0111** [comment]
現実的にはshowにリンクを作って、レビューページを作成した方が良さそうですよね。
名前はおしゃれな雰囲気維持のためにidでも良いかと思います。

**Comment by kubotaseiko** [comment]
@eiji0111 
回答ありがとうございます！
レビューページを作って、非同期通信も実装してみようと思います。
